name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Disable the workflow by default
workflow_dispatch:
  inputs:
    deploy:
      description: 'Deploy to AWS'
      required: true
      default: 'false'
      type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.deploy == true

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Deploy CDK
      run: npm run cdk deploy -- --require-approval never 